services:
  api:
    image: dockethan/lexlingua
    environment:
      SSL_CERT: ${SSL_CERT}
      SSL_CERT_PRIVATE_KEY: ${SSL_CERT_PRIVATE_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SENDER_EMAIL: ${ var.SENDER_EMAIL }
      MAILTRAP_USERNAME: ${ secrets.MAILTRAP_USERNAME }
      MAILTRAP_PASSWORD: ${ secrets.MAILTRAP_PASSWORD }
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:3000"
