services:
  api:
    image: dockethan/lexlingua
    environment:
      SSL_CERT: ${SSL_CERT}
      SSL_CERT_PRIVATE_KEY: ${SSL_CERT_PRIVATE_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
